set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
    CREATE ROLE ${AIRBYTE_PG_USER} LOGIN PASSWORD '${AIRBYTE_PG_PASSWORD}';
    GRANT USAGE ON SCHEMA shop TO ${AIRBYTE_PG_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA shop TO ${AIRBYTE_PG_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA shop GRANT SELECT ON TABLES TO ${AIRBYTE_PG_USER};
SQL
